export enum HttpExceptionEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ACTION_DENIED = 'ACTION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
}

export enum RequestExceptionEnum {
  ASSIGNEE_ID_NOT_EXIST = 'ASSIGNEE_ID_NOT_EXIST',
  REPORTER_ID_NOT_EXIST = 'REPORTER_ID_NOT_EXIST',
  COMPANY_ID_NOT_EXIST = 'COMPANY_ID_NOT_EXIST',
  CUSTOMER_ID_NOT_EXIST = 'CUSTOMER_ID_NOT_EXIST',
  PROJECT_ID_NOT_EXIST = 'PROJECT_ID_NOT_EXIST',
  TICKET_ID_NOT_EXIST = 'TICKET_ID_NOT_EXIST',
  PROJECT_STAGE_ID_NOT_EXIST = 'PROJECT_STAGE_ID_NOT_EXIST',
  PROJECT_REQUEST_TYPE_ID_NOT_EXIST = 'PROJECT_REQUEST_TYPE_ID_NOT_EXIST',

  USER_NOT_IN_PROJECT = 'USER_NOT_IN_PROJECT',
  ASIGNEE_NOT_IN_PROJECT = 'ASIGNEE_NOT_IN_PROJECT',
  REPORTER_NOT_IN_PROJECT = 'REPORTER_NOT_IN_PROJECT',
  TICKET_NOT_IN_PROJECT = 'TICKET_NOT_IN_PROJECT',
  STAGE_NOT_IN_PROJECT = 'STAGE_NOT_IN_PROJECT',
  REQUEST_TYPE_NOT_IN_PROJECT = 'REQUEST_TYPE_NOT_IN_PROJECT',
}
